# **Part A: Conceptual Foundation**

### **1. What is Regularization in Machine Learning? Why is it needed?**

Regularization is a machine learning technique used to reduce model complexity by adding a penalty term to the loss function during training. It helps control overfitting, where a model learns training data too well but fails on unseen data. Regularization improves generalization and makes the model more stable. Common regularization methods include Ridge (L2) and Lasso (L1). It is especially useful when working with datasets having many features.

---

### **2. Difference between Ridge Regression (L2) and Lasso Regression (L1)**

**Ridge Regression (L2):**
- Adds squared coefficient penalty to the cost function.
- Reduces feature weights but keeps all features in the model.
- Useful when most input features contribute to prediction.

**Lasso Regression (L1):**
- Adds absolute coefficient penalty to the cost function.
- Can reduce some coefficients to zero.
- Useful for automatic feature selection and simpler models.

---

### **3. What is Cross-Validation and why is it important?**
Cross-validation is a validation technique used to check how well a machine learning model performs on different parts of data. It helps in selecting a stable model, reducing overfitting, and giving more reliable performance evaluation before final deployment.

---

### **4. Explain the following cross-validation techniques:**

*  **K-Fold Cross-Validation**
The dataset is divided into multiple equal parts called folds. The model is trained using some folds and tested on the remaining fold. This repeats until every fold is used for testing once, and the average result is taken.

*  **Stratified K-Fold Cross-Validation**
This method works like K-Fold but keeps the target distribution balanced in each fold. It provides fair evaluation when the dataset distribution is uneven.

*  **Leave-One-Out Cross-Validation (LOOCV)**
In this method, one sample is used for testing and all remaining samples are used for training. The process repeats until every sample has been tested once. It gives detailed evaluation but takes more computation time.

*  **Time Series Split**
Time Series Split is used when data has a time sequence. Training is done on earlier data and testing is done on later data. This prevents future information from affecting model training.

---

### **5. Why are tree-based models less sensitive to feature scaling?**
Tree-based models like Decision Tree and Random Forest split data based on conditions and threshold values instead of distance calculations. Feature scaling changes the range of values but does not change their order. Because of this, model decisions remain mostly unaffected. Unlike algorithms such as SVR or Linear Regression, scaling is not necessary for tree-based methods. This makes preprocessing simpler.

# **Part B: Dataset Understanding & Preparation**

In [27]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, Lasso, RidgeCV, LassoCV, LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [7]:
df = pd.read_csv("Advanced_Regression_HousePrice_Dataset.csv")
df.head()

,property_id,sale_date,area_sqft,bedrooms,bathrooms,location_score,property_age,distance_city_km,near_school,near_metro,crime_rate_index,house_price_inr
0,200001,2014-01-01,2181,6,4,8.1,21,3.8,0,0,4.84,35154898
1,200002,2019-12-01,2383,5,4,5.3,28,10.9,1,1,2.89,26710893
2,200003,2016-10-01,1047,3,3,5.9,7,27.5,0,1,4.04,11216242
3,200004,2013-03-01,1753,4,3,7.0,27,12.1,0,0,3.28,21984310
4,200005,2013-07-01,1728,4,4,10.0,32,1.4,0,1,3.84,25080429

In [12]:
print("Shape         :", df.shape)
print("Columns name  :",df.columns)

Shape         : (3800, 12)
Columns name  : Index(['property_id', 'sale_date', 'area_sqft', 'bedrooms', 'bathrooms',
       'location_score', 'property_age', 'distance_city_km', 'near_school',
       'near_metro', 'crime_rate_index', 'house_price_inr'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3800 entries, 0 to 3799
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   property_id       3800 non-null   int64
 1   sale_date         3800 non-null   object
 2   area_sqft         3800 non-null   int64
 3   bedrooms          3800 non-null   int64
 4   bathrooms         3800 non-null   int64
 5   location_score    3800 non-null   float64
 6   property_age      3800 non-null   int64
 7   distance_city_km  3800 non-null   float64
 8   near_school       3800 non-null   int64
 9   near_metro        3800 non-null   int64
 10  crime_rate_index  3800 non-null   float64
 11  house_price_inr   3800 non-null   int64
dtypes: float64(3), int64(8), object(1)
memory usage: 356.4+ KB

In [16]:
df.describe()

,property_id,area_sqft,bedrooms,bathrooms,location_score,property_age,distance_city_km,near_school,near_metro,crime_rate_index,house_price_inr
count,3800.00000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3.800000e+03
mean,201900.50000,1716.925526,3.428158,2.916316,6.502237,22.537105,13.085132,0.548421,0.472895,4.242911,2.071940e+07
std,1097.10984,582.996559,1.356682,1.133540,1.766945,12.325740,6.537425,0.497715,0.499330,2.045371,8.707465e+06
min,200001.00000,500.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.500000,1.506126e+06
25%,200950.75000,1322.000000,2.000000,2.000000,5.300000,14.000000,8.500000,0.000000,0.000000,2.810000,1.446895e+07
50%,201900.50000,1700.500000,3.000000,3.000000,6.500000,20.000000,13.000000,1.000000,0.000000,4.220000,1.989180e+07
75%,202850.25000,2105.000000,4.000000,4.000000,7.700000,29.000000,17.500000,1.000000,1.000000,5.650000,2.596062e+07
max,203800.00000,3776.000000,7.000000,6.000000,10.000000,80.000000,38.700000,1.000000,1.000000,12.000000,5.930315e+07

### 6. Identify features and target variable

In [18]:
features = ['area_sqft', 'bedrooms', 'bathrooms', 'location_score','property_age', 'distance_city_km', 'near_school','near_metro', 'crime_rate_index']
target   = 'house_price_inr'

print("Features :", features)
print("Target   :", target)

Features : ['area_sqft', 'bedrooms', 'bathrooms', 'location_score', 'property_age', 'distance_city_km', 'near_school', 'near_metro', 'crime_rate_index']
Target   : house_price_inr

In [19]:
X = df[features]
y = df[target]

### 7. Train-Test Split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print("X_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)
print("y_train Shape:", y_train.shape)
print("y_test Shape:", y_test.shape)

X_train Shape: (3040, 9)
X_test Shape: (760, 9)
y_train Shape: (3040,)
y_test Shape: (760,)

### 8: Basic Preprocessing (Scaling)

In [21]:
scal = StandardScaler()
X_train_scal = scal.fit_transform(X_train)
X_test_scal = scal.transform(X_test)

# **Part C: Regularized Linear Models**

In [32]:
results = []

def evaluate_model(model, model_name, X_train, X_test, y_train, y_test):

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    print(f"{model_name} Results:")
    print()
    print(f"MSE: {mse:.2f}")
    print(f"RMSE: {rmse:.2f}")
    print(f"MAE: {mae:.2f}")
    print(f"R2 Score: {r2:.2f}")

    results.append([model_name, mse, rmse, mae, r2])

    return model

### 9. Ridge Regression (L2)

In [33]:
ridge = Ridge(alpha=1.0)

l2 = evaluate_model(ridge,"Ridge Regression (L2)", X_train_scal, X_test_scal, y_train, y_test)

Ridge Regression (L2) Results:

MSE: 6545419443619.51
RMSE: 2558401.74
MAE: 1959198.97
R2 Score: 0.92

### 10. Lasso Regression (L1)

In [38]:
lasso = Lasso(alpha=1.0)

l1 = evaluate_model(lasso,"Lasso Regression (L1)", X_train_scal, X_test_scal, y_train, y_test)

Lasso Regression (L1) Results:

MSE: 6543996619352.28
RMSE: 2558123.65
MAE: 1959378.45
R2 Score: 0.92

### 11. Tune alpha using Cross Validation

# **Part D: Cross-Validation Strategies**

# **Part E: Tree-Based Regression Models**

# **Part F: Support Vector Regression**

# **Part G: Model Comparison & Evaluation**

# **Part H: Final Analysis & Reporting**